# Version of circle ci to use
version: 2.1

# A workflow is comprised of one or more uniquely named jobs.
jobs:
  build-test: # name of the job
    working_directory: ~/repo # In which directory to run the steps. Will be interpreted as an absolute path.
    docker: # to use a circle ci pre-built docker file
      - image: cimg/node:16.15.0 # name of the image to run --> note js version 16.15.0
    steps: # list of steps as single key/value pairs
      - checkout # used to checkout the code from the specified directory (working_directory)
      - run: # key --> indicates the step type
          name: Install Dependencies # name of the step (not required)
          command: npm install # defines the command to execute at this step
      - run:
          name: Test
          command: npm run test

workflows: # used for orchestrating all jobs
  version: 2.1
  build-test: # job name that exists in the config.yml
    jobs: # list of jobs to run that must succeed
      - build-test
